wsl convert houghcircles_color_output.ppm houghcircles_color_output.png
wsl convert houghcircles_edges_output.ppm houghcircles_edges_output.png
wsl convert houghcircles_votes_output.ppm houghcircles_votes_output.png